name: Lint

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt
          pip install -r dev/requirements.txt

      - name: Lint
        run: |
          pre-commit run --all-files 2> /dev/null
          ec=$?
          git diff -U0 > log.txt && cat log.txt
          exit $ec